version: '3.1'

services:
  app:
    build: .
    container_name: sword-health
    depends_on:
      - db
    ports:
      - 23412:23412
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=swordhealth@2023
      - DB_DATABASE=swordhealthDB
      - DB_PORT=3306
      - WAIT_HOSTS=db:3306
    volumes:
      - .:/src/
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=swordhealth@2023
      - MYSQL_DATABASE=swordhealthDB
    ports:
      - "3306:3306"
    volumes:
      - ./src/database:/app/api
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=swordhealth2023